In [1]:
import pandas as pd

df = pd.read_csv(r'P:\weather-lstm-project\data\india_2000_2024_daily_weather.csv')
df.head()

<>:3: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
<>:3: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
C:\Users\Soham\AppData\Local\Temp\ipykernel_26632\913315399.py:3: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
  df = pd.read_csv('P:\weather-lstm-project\data\india_2000_2024_daily_weather.csv')

,city,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,weather_code,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant
0,Delhi,2000-01-01,19.9,7.4,19.2,5.8,0.0,0.0,0,10.9,13.3,58
1,Delhi,2000-01-02,20.0,5.5,18.9,3.4,0.0,0.0,3,9.5,14.8,326
2,Delhi,2000-01-03,20.1,6.3,18.2,4.3,0.0,0.0,0,10.0,23.8,309
3,Delhi,2000-01-04,19.8,6.4,18.5,4.2,0.0,0.0,0,8.6,18.7,311
4,Delhi,2000-01-05,19.4,5.3,17.7,3.2,0.0,0.0,0,9.4,20.2,322

In [3]:
df.shape

(91320, 12)

In [4]:
df.columns

Index(['city', 'date', 'temperature_2m_max', 'temperature_2m_min',
       'apparent_temperature_max', 'apparent_temperature_min',
       'precipitation_sum', 'rain_sum', 'weather_code', 'wind_speed_10m_max',
       'wind_gusts_10m_max', 'wind_direction_10m_dominant'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 91320 entries, 0 to 91319
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   city                         91320 non-null  str
 1   date                         91320 non-null  str
 2   temperature_2m_max           91320 non-null  float64
 3   temperature_2m_min           91320 non-null  float64
 4   apparent_temperature_max     91320 non-null  float64
 5   apparent_temperature_min     91320 non-null  float64
 6   precipitation_sum            91320 non-null  float64
 7   rain_sum                     91320 non-null  float64
 8   weather_code                 91320 non-null  int64
 9   wind_speed_10m_max           91320 non-null  float64
 10  wind_gusts_10m_max           91320 non-null  float64
 11  wind_direction_10m_dominant  91320 non-null  int64
dtypes: float64(8), int64(2), str(2)
memory usage: 8.4 MB

In [6]:
df['city'].unique()

<StringArray>
[    'Delhi',    'Mumbai',   'Kolkata',   'Chennai', 'Bangalore', 'Hyderabad',
 'Ahmedabad',      'Pune',    'Jaipur',   'Lucknow']
Length: 10, dtype: str

In [9]:
df['date'].head()

0   2000-01-01
1   2000-01-02
2   2000-01-03
3   2000-01-04
4   2000-01-05
Name: date, dtype: datetime64[us]

In [8]:
df['date'] = pd.to_datetime(df['date'])

In [10]:
df = df.sort_values(by=['city', 'date'])

In [11]:
df.head()

,city,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,weather_code,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant
54792,Ahmedabad,2000-01-01,29.9,15.3,29.1,12.8,0.0,0.0,0,14.5,30.2,60
54793,Ahmedabad,2000-01-02,29.9,16.1,28.8,13.2,0.0,0.0,0,15.3,29.5,68
54794,Ahmedabad,2000-01-03,29.1,15.1,27.9,12.1,0.0,0.0,0,14.4,27.7,52
54795,Ahmedabad,2000-01-04,28.6,13.7,27.5,11.2,0.0,0.0,0,12.4,21.6,45
54796,Ahmedabad,2000-01-05,28.1,13.2,26.8,10.8,0.0,0.0,0,11.3,22.7,34

In [12]:
df.isnull().sum()

city                           0
date                           0
temperature_2m_max             0
temperature_2m_min             0
apparent_temperature_max       0
apparent_temperature_min       0
precipitation_sum              0
rain_sum                       0
weather_code                   0
wind_speed_10m_max             0
wind_gusts_10m_max             0
wind_direction_10m_dominant    0
dtype: int64

In [13]:
city_df = df[df['city'] == df['city'].unique()[0]]
city_df.head(50)

,city,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,weather_code,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant
54792,Ahmedabad,2000-01-01,29.9,15.3,29.1,12.8,0.0,0.0,0,14.5,30.2,60
54793,Ahmedabad,2000-01-02,29.9,16.1,28.8,13.2,0.0,0.0,0,15.3,29.5,68
54794,Ahmedabad,2000-01-03,29.1,15.1,27.9,12.1,0.0,0.0,0,14.4,27.7,52
54795,Ahmedabad,2000-01-04,28.6,13.7,27.5,11.2,0.0,0.0,0,12.4,21.6,45
54796,Ahmedabad,2000-01-05,28.1,13.2,26.8,10.8,0.0,0.0,0,11.3,22.7,34
54797,Ahmedabad,2000-01-06,28.1,13.6,26.6,11.3,0.0,0.0,0,12.1,24.1,40
54798,Ahmedabad,2000-01-07,28.9,12.4,27.1,10.2,0.0,0.0,0,10.7,21.6,63
54799,Ahmedabad,2000-01-08,29.4,12.8,28.3,10.7,0.0,0.0,0,9.7,15.8,44
54800,Ahmedabad,2000-01-09,29.7,11.9,29.0,10.2,0.0,0.0,1,10.0,14.4,25
54801,Ahmedabad,2000-01-10,29.8,13.2,29.5,12.0,0.0,0.0,0,8.7,18.4,37
54802,Ahmedabad,2000-01-11,31.1,14.3,30.7,12.8,0.0,0.0,0,8.4,18.4,72
54803,Ahmedabad,2000-01-12,26.9,15.9,25.9,15.7,0.0,0.0,1,13.1,27.0,273
54804,Ahmedabad,2000-01-13,26.5,15.8,24.2,13.9,0.0,0.0,0,12.4,29.2,330
54805,Ahmedabad,2000-01-14,25.6,11.5,23.8,9.2,0.0,0.0,0,9.7,22.0,350
54806,Ahmedabad,2000-01-15,24.9,10.9,22.1,7.4,0.0,0.0,0,13.0,28.4,5
54807,Ahmedabad,2000-01-16,25.2,12.7,21.5,7.6,0.0,0.0,0,19.4,39.2,41
54808,Ahmedabad,2000-01-17,26.4,13.5,23.0,8.3,0.0,0.0,0,21.7,41.0,56
54809,Ahmedabad,2000-01-18,29.9,16.0,28.9,11.6,0.0,0.0,0,17.4,34.2,65
54810,Ahmedabad,2000-01-19,30.8,15.3,30.7,14.5,0.0,0.0,0,12.7,25.2,348
54811,Ahmedabad,2000-01-20,29.0,12.1,26.8,10.1,0.0,0.0,0,10.2,22.0,310
54812,Ahmedabad,2000-01-21,26.9,13.3,27.7,12.6,0.0,0.0,3,9.7,22.3,259
54813,Ahmedabad,2000-01-22,27.5,15.1,27.8,15.5,0.0,0.0,2,9.7,24.1,281
54814,Ahmedabad,2000-01-23,28.8,14.3,29.5,14.4,0.0,0.0,0,9.0,18.0,27
54815,Ahmedabad,2000-01-24,29.7,14.6,30.0,13.8,0.0,0.0,0,8.6,17.3,19
54816,Ahmedabad,2000-01-25,30.0,13.8,29.6,13.2,0.0,0.0,0,8.4,20.2,349
54817,Ahmedabad,2000-01-26,29.7,13.8,30.4,13.2,0.0,0.0,0,10.8,18.4,346
54818,Ahmedabad,2000-01-27,27.8,16.3,25.3,13.7,0.0,0.0,0,15.6,33.8,20
54819,Ahmedabad,2000-01-28,26.5,13.7,22.9,9.9,0.0,0.0,0,18.7,37.4,44
54820,Ahmedabad,2000-01-29,27.7,12.9,25.0,8.8,0.0,0.0,0,16.2,32.4,56
54821,Ahmedabad,2000-01-30,29.5,10.8,28.5,8.2,0.0,0.0,0,9.0,19.1,34
54822,Ahmedabad,2000-01-31,28.2,11.4,26.6,9.1,0.0,0.0,1,12.6,27.0,257
54823,Ahmedabad,2000-02-01,27.3,15.4,27.4,16.2,0.0,0.0,2,11.1,21.2,240
54824,Ahmedabad,2000-02-02,27.6,15.1,27.4,16.7,0.0,0.0,3,11.8,25.2,180
54825,Ahmedabad,2000-02-03,27.3,14.3,27.6,14.5,0.0,0.0,1,8.7,23.0,270
54826,Ahmedabad,2000-02-04,27.7,14.8,27.2,14.7,0.0,0.0,1,16.3,28.4,277
54827,Ahmedabad,2000-02-05,25.4,16.4,23.0,13.6,0.0,0.0,2,15.1,28.8,330
54828,Ahmedabad,2000-02-06,25.7,12.4,24.5,10.0,0.0,0.0,0,11.1,25.2,22
54829,Ahmedabad,2000-02-07,26.8,13.5,25.2,10.3,0.0,0.0,2,15.4,32.8,41
54830,Ahmedabad,2000-02-08,27.3,13.1,26.2,10.6,0.0,0.0,2,11.7,23.8,14
54831,Ahmedabad,2000-02-09,28.5,13.7,28.1,11.1,0.0,0.0,0,11.5,24.5,30
54832,Ahmedabad,2000-02-10,28.7,13.3,28.4,11.5,0.0,0.0,2,15.9,32.0,279
54833,Ahmedabad,2000-02-11,26.0,15.2,23.1,12.7,0.0,0.0,0,16.0,34.9,324
54834,Ahmedabad,2000-02-12,25.7,12.4,23.7,9.4,0.0,0.0,0,11.4,23.4,31
54835,Ahmedabad,2000-02-13,26.3,12.6,23.8,8.2,0.0,0.0,0,18.0,36.4,33
54836,Ahmedabad,2000-02-14,26.4,13.9,23.6,9.2,0.0,0.0,0,20.9,41.0,46
54837,Ahmedabad,2000-02-15,28.2,13.7,26.9,9.2,0.0,0.0,0,18.1,36.4,45
54838,Ahmedabad,2000-02-16,29.2,13.1,26.4,10.3,0.0,0.0,0,13.1,28.8,345
54839,Ahmedabad,2000-02-17,29.2,12.3,27.2,9.6,0.0,0.0,0,9.8,20.2,1
54840,Ahmedabad,2000-02-18,29.4,12.4,28.7,9.7,0.0,0.0,0,9.0,20.2,82
54841,Ahmedabad,2000-02-19,30.0,12.8,29.3,11.1,0.0,0.0,0,9.4,21.6,61

In [29]:
import sys
import os

sys.path.append(os.path.abspath('..'))

In [31]:
from src.preprocessing import load_data, encode_city, scale_features

df = load_data(r'P:\weather-lstm-project\data\india_2000_2024_daily_weather.csv')

feature_cols = [
    'temperature_2m_max',
    'temperature_2m_min',
    'apparent_temperature_max',
    'apparent_temperature_min',
    'precipitation_sum',
    'rain_sum',
    'weather_code',
    'wind_speed_10m_max',
    'wind_gusts_10m_max',
    'wind_direction_10m_dominant'
]

df, le = encode_city(df)
df, scaler = scale_features(df, feature_cols)

df.head()

ImportError: cannot import name 'load_data' from 'src.preprocessing' (p:\weather-lstm-project\src\preprocessing.py)

In [25]:
import sys
sys.path.append('..')

import src.preprocessing as p

print(p.__file__)
print(dir(p))

p:\weather-lstm-project\src\preprocessing.py
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']

In [33]:
feature_cols = [
    'temperature_2m_max',
    'temperature_2m_min',
    'apparent_temperature_max',
    'apparent_temperature_min',
    'precipitation_sum',
    'rain_sum',
    'weather_code',
    'wind_speed_10m_max',
    'wind_gusts_10m_max',
    'wind_direction_10m_dominant'
]

In [34]:
from src.dataset import create_sequences

X, y = create_sequences(df, feature_cols)

print(X.shape)
print(y.shape)

(90950, 30, 10)
(90950, 7, 10)

In [35]:
from src.dataset import WeatherDataset

dataset = WeatherDataset(X, y)

print(len(dataset))
sample_X, sample_y = dataset[0]

print(sample_X.shape)
print(sample_y.shape)

ImportError: cannot import name 'WeatherDataset' from 'src.dataset' (p:\weather-lstm-project\src\dataset.py)